import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster
          position="top-left"
          toastOptions={{
            duration: 5000,

            error: {
              style: {
                border: "1px solid #FF542F",
                background: "#04061C",
                color: "white",
              },
            },

            success: {
              style: {
                border: "1px solid #4CAF50",
                background: "#04061C",
                color: "white",
              },
            },

            loading: {
              style: {
                border: "1px solid #FFEB3B",
                background: "#04061C",
                color: "white",
              },
            },

            className: "bg-black",
            custom: {
              style: {
                border: "1px solid #FF542F",
                padding: "16px",
                color: "#04061C",
                background: "black",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
